name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm ci

    - name: Build React App
      run: npm run build

    - name: Deploy to EC2
      env:
        EC2_HOST: "ubuntu@<EC2_PUBLIC_IP>"
        EC2_PATH: "/var/www/html"
      run: |
        echo "$EC2_SSH_KEY" > ssh_key
        chmod 600 ssh_key
        scp -i ssh_key -r build/* $EC2_HOST:$EC2_PATH
        ssh -i ssh_key $EC2_HOST "sudo systemctl restart nginx"

